### ISSUE TITLE
Game crash when clicking on windows/borderless in System Settings

### ISSUE THREAD

**Issue by ghost** [Helios747/AdaptiveHudPlugin#1]
What title says. No clue if this is going to help but here's the appcrash.log too: [dalamud_appcrash.log](https://github.com/Helios747/AdaptiveHudPlugin/files/9301668/dalamud_appcrash.log)

![image](https://user-images.githubusercontent.com/63500907/183950552-04383508-a432-4cbf-adcd-7e87f90dbca1.png)

**Comment by Helios747** [comment]
Hi, I completely missed this, this should be fixed as of 6.2
