### ISSUE TITLE
Please update it for 6.5

### ISSUE THREAD

**Issue by AngelFireOmega** [Helios747/AdaptiveHudPlugin#2]
Please update for 6.5. I need it. Thanks

**Comment by Helios747** [comment]
huh, didn't know anybody actually used my niche thing.

I'll work on getting it fixed. API9 came with some significant changes and I really don't know .NET all that well so it'll take me a bit to figure it out.

**Comment by Helios747** [comment]
Fixed as of https://github.com/Helios747/AdaptiveHudPlugin/commit/2281bea1bcca392caa7b2cd7d359e3bc7de18ec2

Plugin is built and should be live in Dalamud repos in the next few hours!
